### ISSUE TITLE
Can't join

### ISSUE THREAD

**Issue by kfatehi** [railslink/railslink#160]
Signed up but can't join.

**Comment by kfatehi** [comment]
I hope whoever reads this appreciates my humor and style rather than gets upset. I am upset about the fact that a brilliant IRC community has fractured into silos that newbies can't even enter to get help, such as this one, so then what is the point if new users cannot come and gain from the knowledge of the experienced ? What is the point of the group for the experienced people if not to concentrate knowledge for the newbies? By excluding newbies by not having automatic enrollment for new prospective members it just reeks of elitism.

**Comment by cata0309** [comment]
I am in the same situation. I am still waiting for a manual approval. I don't know who to contact!

**Comment by cata0309** [comment]
@nauman can you help me?

**Comment by nauman** [comment]
Please check junk email as well

**Comment by cata0309** [comment]
Thank you! I received the invitation!
