### ISSUE TITLE
Not receiving an invite from Slack

### ISSUE THREAD

**Issue by ayushn21** [railslink/railslink#32]
Hi,

Apologies if this isn't the right way to bring up this issue. I've filled out the form on your website a number of times and even tried using 2 different email addresses; but haven't received the invitation email from Slack. Could you please help with this?

Thanks,
Ayush

**Comment by nauman** [comment]
Hi,

You have been invited already please check your spam folder
![image](https://cloud.githubusercontent.com/assets/90499/23488148/f2df88ba-ff3e-11e6-85d3-2fd80faeee0e.png)

**Comment by ayushn21** [comment]
Thanks @nauman. I've received the email on my gmail address now somehow. It arrived a few hours after I filled the form. Thanks for your help :)
