### ISSUE TITLE
Enable automatic gem security scans in CircleCI

### ISSUE THREAD

**Issue by phallstrom** [railslink/railslink#37]
See: https://rietta.com/blog/2018/07/18/automate-scheduled-security-scans-with-circleci/

**Comment by cchoi12** [comment]
Feel free to DM me on RailsLink if you need any help/clarification, I was OP for the blog post :).

**Comment by arun1595** [comment]
@phallstrom I would like to tackle this task.

**Comment by phallstrom** [comment]
@arun1595 sweet! Go ahead and open a PR

**Comment by arun1595** [comment]
@phallstrom Working on it, will submit a PR soon.
