### ISSUE TITLE
Migrate from CircleCI 1.0 to 2.0

### ISSUE THREAD

**Issue by phallstrom** [railslink/railslink#41]
See https://circleci.com/docs/2.0/migration/

**Comment by pachonk** [comment]
The config is already 2.0

**Comment by pachonk** [comment]
Though they have a new 2.1 spec coming out soon

**Comment by phallstrom** [comment]
So might just be it's in the wrong spot? Something is wrong since we're not getting any new builds...

**Comment by phallstrom** [comment]
Turns out this was a YAML config error, not a v1 vs v2 issue.
