### ISSUE TITLE
Create a users/channels admin interface

### ISSUE THREAD

**Issue by katelovescode** [railslink/railslink#46]
There isn't a users or channels admin interface at all.  not that we should allow changing stuff, but it might be nice to flesh out an index and/or let admins search and stuff in preparation for future things

**Comment by phallstrom** [comment]
A lot of the view code for approving membership submissions can probably be co-opted pretty easily for the user admin interface.

**Comment by brandondees** [comment]
I'm not clear on what kinds of actions we're able to perform through the APIs yet, but just having a nice way to browse the data read-only might be handy. Eventually we'll probably start looking for ways to do management tasks beyond approving join requests, maybe look up inactives for removal, search profile details, etc.

**Comment by phallstrom** [comment]
For now I would focus on the index screen, searching, and a show/edit screen that's non-functional.  Like the pending memberships. It's all there, but you can't change any of it.

I don't think it's worth trying to re-implement the things we could do in Slack like set a channel topic, but this lays the groundwork for future outside-of-slack things we may want to do.  User profiles, some nifty graphs by channel, etc.

**Comment by phallstrom** [comment]
This is mostly all done via 1de1fb8a300219b06fdf890826f0c96b0e3a3eb1

Closing it and we can open new tickets for additional functionality.
