### ISSUE TITLE
Implement navbar hamburger menu functionality.

### ISSUE THREAD

**Issue by phallstrom** [railslink/railslink#50]
The website uses the Bulma CSS framework. If you visit https://www.rubyonrails.link/join-now you'll see a nav bar at the top. If you narrow your window that navbar stacks, but does not turn into a hamburger. This functionality is available as part of Bulma, but we never implemented it.

https://bulma.io/documentation/components/navbar/

**Comment by Talha5** [comment]
@phallstrom I think we should close this issue now as #51 and #52 Fixes it.

**Comment by phallstrom** [comment]
Doh. Forgot about this. Will do. Thanks @Talha5 !
