### ISSUE TITLE
Create ephemeral welcome message for #work-offers

### ISSUE THREAD

**Issue by phallstrom** [railslink/railslink#54]
In order to help keep #work-offers focused we would like to create an ephemeral welcome message when people join that channel.

Initial suggestion for that message is below:

> Welcome to the Ruby on Rails Link community's job posting channel. This channel is specifically for posting job opportunities. Feel free to post job offers or job-seeking information here. Be courteous and do not cross-post to other channels or flood this channel with too many posts for a given work opportunity. Repeating the same post is allowed if the previous one has been removed from the slack history or hasn't been seen for a reasonably long period of time (at least a full day, preferably longer). Slack threads are recommended for followup details or discussion of a given offer, to reduce the amount of noise in the channel while allowing the additional information to be seen by others who may be interested. When posting a job offer here, it's recommended to clearly state whether the job is remote-friendly or if localized, where, and whether any relocation accommodations are available. For all discussion of jobs, workplaces, career paths, etc. _other_ than work opportunities, please use #work-career-chat

**Comment by brandondees** [comment]
i drafted this message, would love some proofing and refinement suggestions, or anybody is welcome to write their own alternative to propose at any time, of course.

**Comment by phallstrom** [comment]
Got a WIP working locally.

<img width="596" alt="screen shot 2018-10-23 at 9 53 20 pm" src="https://user-images.githubusercontent.com/16705/47407043-1bc1cd80-d70e-11e8-9051-c27241e0e942.png">

**Comment by phallstrom** [comment]
With some better formatting.  I think we may want to trim some of the copy down so folks don't skip it.  Will see what editing I can do when I'm not as tired.

<img width="677" alt="screen shot 2018-10-23 at 9 55 41 pm" src="https://user-images.githubusercontent.com/16705/47407100-67747700-d70e-11e8-90d4-799275d505de.png">

**Comment by phallstrom** [comment]
@brandondees I took your draft and probably butchered it.  With a goal of assuming people won't read so striving for brevity while also moving the most critical components closer to the top.  Let me know what you think...

>         Welcome to our job posting channel. This channel is specifically for
>         posting job offers or job-seeking information.
> 
>         For all other discussion of jobs, workplaces, career paths, etc. other
>         than work opportunities, please use #work-career-chat.
> 
>         Your job offer should include the location, remote friendliness,
>         company name, as well as instructions on how to apply.
> 
>         Be courteous and do not cross-post to other channels or post repeatedly
>         for the same job offer. Do not pin your job post.
> 
>         Please use Slack threads to followup to keep the main channel's signal
>         to noise ratio high.
>
