### ISSUE TITLE
Move from controller specs to request specs

### ISSUE THREAD

**Issue by katelovescode** [railslink/railslink#66]
Currently we're using controller specs; we should switch to request specs so we hit the whole stack including routing.

**Comment by arun1595** [comment]
@phallstrom I would like to take a stab at this.

**Comment by arun1595** [comment]
@phallstrom What do you think of this splitting this task into a couple of tasks?

ie. migrating specs to of admin namespaced controllers to request specs and the rest

**Comment by phallstrom** [comment]
Seems reasonable to me.  If you wanna open up individual PR's and simply reference this ticket that's fine.

**Comment by arun1595** [comment]
Cool, let me get started.
