### ISSUE TITLE
Create a slash command or integration to display a list of admins to any user

### ISSUE THREAD

**Issue by katelovescode** [railslink/railslink#81]
Notes from discussion w/ @phallstrom in `#railslink-dev`:

> - slack commands are handled differently than web events.  There's something you have to configure in Slack itself to enable it (the command, the endpoint, etc.).  I think if we do this we should setup a similar general API endpoint for all the commands (as the command comes through in the params as well) to mirror what we do for the web end point.
> - The other thing I noticed is that while we _can_ verify the request using the same token stuff we do now for events, they recommend doing it a new way (it's in their docs).  So we might want to explore that and abstract that out for both of them.
> - So my preference would be a POST request to `/slack/command` which then figured out what to do based on the param[:command].

Implementation detail:
probably should randomize the order so the person at the top alphabetically doesn't get all the requests, per suggestion in the admin channel

**Comment by phallstrom** [comment]
This was completed via #99
