### ISSUE TITLE
Create an endpoint on the site to display admins

### ISSUE THREAD

**Issue by katelovescode** [railslink/railslink#85]
rubyonrails.link/admins should display a list of current admins (and maybe a "contact" button/form to contact them directly from there?)

**Comment by blueyedgeek** [comment]
Hi @katelovescode, I'd started looking into implementing this endpoint (and the relevant page that should go with it) and I realised that a `/admin` endpoint already exists. Now, while the endpoint already exists, the relevant page is just a default rails starter template. 

I was wondering if it was safe/okay to point the endpoint to a different controller or to just use a different endpoint entirely (maybe `/contact`). Advise to proceed?

**Comment by brandondees** [comment]
I'd prefer to keep the rest/rails conventions and semantics proper as much as possible, but we may need to distinguish between "administrative area of the site" and public-facing admin index with a namespace or that type of thing. it might be helpful to disambiguate the name more with something like `/admin_members`
