### ISSUE TITLE
Slack Invite not sure if im at the right slack channel

### ISSUE THREAD

**Issue by nickclasener** [railslink/railslink#89]
I've signed up @ https://www.rubyonrails.link 
My focus pertains stimulus/Turbolinks.
I am a Junior/Medior developer Focused on Laravel.
Currently in the progress of building an app with Laravel/Stimulus.
And in search of some feedback, on the way I've implemented Stimulus.
I signed up because stimulus/Turbolinks are from the rails community.
That being said i'm unsure if the rails slack is the proper channel.
If it's not my apologies for the inconvenience.

**Comment by phallstrom** [comment]
@nickclasener We're more focused on ruby/rails, but you'll find folks that talk about stimulus/turbolinks. You're more than welcome to join and try it out and if it's not for you, no worries.
