### ISSUE TITLE
Notify nightly circleci build (security audit) on failure only

### ISSUE THREAD

**Issue by grepsedawk** [railslink/railslink#91]
Only a suggestion and I'm willing to discuss further, but I personally feel that the nightly build would be more valuable if it only notified on failure

**Comment by phallstrom** [comment]
Pretty sure I just flipped a switch that will resolve this.

<img width="252" alt="image" src="https://user-images.githubusercontent.com/16705/54871640-de24a780-4d74-11e9-8013-755f3805ff23.png">
